name: Run tests
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.julia-version == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        julia-version:
          - '1.3'
          - '1.4'
          - '1.5'
          - '1.6'
          - 'nightly'
        julia-arch:
          - x64
        os:
          - ubuntu-latest
          - macOS-latest
            #- windows-latest
        exclude:
          # Reduce the number of macOS jobs, as fewer can be run in parallel
          - os: macOS-latest
            julia-version: '1.3'
          - os: macOS-latest
            julia-version: '1.4'
          - os: macOS-latest
            julia-version: '1.5'

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - name: Build package
        uses: julia-actions/julia-buildpkg@latest
      - name: Run tests
        uses: julia-actions/julia-runtest@latest

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-docdeploy@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
