name: Documentation
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - name: Install Singular
        run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec("Singular"))
            Pkg.instantiate()'
      - run: sed -i 's/libsingular_julia_jll = "~0.9.200"/libsingular_julia_jll = "~0.11.0"/' ~/.julia/dev/Singular/Project.toml
      - name: Install dependencies
        run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=docs docs/make.jl
